import { MigrationInterface, QueryRunner } from 'typeorm';

// Auto-generated by `pnpm run migration:generate` against the entities in
// src/**/entities, then hand-edited (see comments below) — per
// docs/adr/0002-data-model.md ("schema changes go through migrations,
// never manual edits to a running schema").
//
// Two edits on top of the raw generator output:
//  1. Deduped the `parental_consent_status_enum` Postgres enum type, which
//     both Player.parental_consent_status and ParentalConsentRecord.status
//     map to — the generator emitted a CREATE TYPE (and matching DROP TYPE)
//     for it once per entity, which would fail on the second CREATE.
//  2. Added explicit foreign-key constraints for every *_id column. This
//     project's entities use plain scalar id columns (not TypeORM relation/
//     @JoinColumn decorators — a deliberate simplicity choice, see the
//     Phase 1 handoff notes), so the generator doesn't infer FKs on its
//     own; they're added by hand here instead.
export class InitialSchema1783108774127 implements MigrationInterface {
  name = 'InitialSchema1783108774127';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "public"."activity_type_enum" AS ENUM('fitness', 'drill', 'running', 'other')`,
    );
    await queryRunner.query(
      `CREATE TABLE "training_log_entry" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "player_id" uuid NOT NULL, "team_id" uuid NOT NULL, "logged_at" TIMESTAMP WITH TIME ZONE NOT NULL, "activity_type" "public"."activity_type_enum" NOT NULL, "duration_minutes" integer NOT NULL, "challenge_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_17ac48fce9b1f6231290f08f0df" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_4cf1a9969fa2a43f4b4f3416c2" ON "training_log_entry" ("team_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_913379111b6efeadd470484567" ON "training_log_entry" ("player_id", "logged_at") `,
    );
    await queryRunner.query(
      `CREATE TABLE "team" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "name" character varying NOT NULL, "invite_code" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_da387f0c2e17d1e1e09f2836adf" UNIQUE ("invite_code"), CONSTRAINT "PK_f57d8293406df4af348402e4b74" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "team_coach" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "team_id" uuid NOT NULL, "coach_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b2cccee84bc219af212d6590173" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_b97de386b953752f7897d45094" ON "team_coach" ("team_id", "coach_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "season" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "team_id" uuid NOT NULL, "label" character varying NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, CONSTRAINT "PK_8ac0d081dbdb7ab02d166bcda9f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."parental_consent_status_enum" AS ENUM('not_requested', 'pending', 'approved', 'revoked')`,
    );
    await queryRunner.query(
      `CREATE TABLE "player" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "team_id" uuid NOT NULL, "screen_name" character varying NOT NULL, "avatar_id" character varying NOT NULL, "birth_year" smallint NOT NULL, "parental_consent_status" "public"."parental_consent_status_enum" NOT NULL DEFAULT 'pending', "current_streak_count" integer NOT NULL DEFAULT '0', "longest_streak_count" integer NOT NULL DEFAULT '0', "last_trained_date" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_65edadc946a7faf4b638d5e8885" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_b3c76b4d48cefcb7aa46feb1ee" ON "player" ("team_id", "screen_name") `,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."team_season_pot_status_enum" AS ENUM('active', 'achieved', 'closed')`,
    );
    await queryRunner.query(
      `CREATE TABLE "team_season_pot" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "team_id" uuid NOT NULL, "season_id" uuid NOT NULL, "points_total" integer NOT NULL DEFAULT '0', "goal_threshold" integer NOT NULL, "status" "public"."team_season_pot_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_83dfe9b328972b47415487e2ad8" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_4ac675ceabf9c0fe1cc21cb232" ON "team_season_pot" ("team_id", "status") `,
    );
    await queryRunner.query(
      `CREATE TABLE "player_private_info" ("player_id" uuid NOT NULL, "real_name" character varying, "parent_contact" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f26347e01cb431a445c22cf3da6" PRIMARY KEY ("player_id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."consent_method_enum" AS ENUM('email_link', 'in_app_by_parent_account')`,
    );
    await queryRunner.query(
      `CREATE TABLE "parental_consent_record" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "player_id" uuid NOT NULL, "status" "public"."parental_consent_status_enum" NOT NULL, "method" "public"."consent_method_enum" NOT NULL, "recorded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_216c9e4204d6cad4e33df8a07d1" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "coach" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "email" character varying NOT NULL, "display_name" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a1583a1abd23efb2f821c096780" UNIQUE ("email"), CONSTRAINT "PK_c2ca0875fe0755b197d0147713d" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."challenge_status_enum" AS ENUM('draft', 'active', 'completed', 'cancelled')`,
    );
    await queryRunner.query(
      `CREATE TABLE "challenge" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "team_id" uuid NOT NULL, "created_by_coach_id" uuid NOT NULL, "title" character varying NOT NULL, "description" character varying NOT NULL, "target_metric" character varying NOT NULL, "target_value" integer NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "status" "public"."challenge_status_enum" NOT NULL DEFAULT 'draft', CONSTRAINT "PK_5f31455ad09ea6a836a06871b7a" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "badge" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "key" character varying NOT NULL, "display_name" character varying NOT NULL, "description" character varying NOT NULL, "icon" character varying NOT NULL, CONSTRAINT "UQ_cd1ded2fd33180834cc77bd9f98" UNIQUE ("key"), CONSTRAINT "PK_76b7011c864d4521a14a5196c49" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "badge_award" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "player_id" uuid NOT NULL, "badge_id" uuid NOT NULL, "awarded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "context" jsonb NOT NULL, "awarded_by" character varying NOT NULL, CONSTRAINT "PK_905e0f63629efad9602c0bdfef6" PRIMARY KEY ("id"))`,
    );

    // --- Foreign keys (hand-added, see class-level comment) -----------------
    await queryRunner.query(
      `ALTER TABLE "player" ADD CONSTRAINT "FK_player_team" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "player_private_info" ADD CONSTRAINT "FK_player_private_info_player" FOREIGN KEY ("player_id") REFERENCES "player"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "parental_consent_record" ADD CONSTRAINT "FK_parental_consent_record_player" FOREIGN KEY ("player_id") REFERENCES "player"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_coach" ADD CONSTRAINT "FK_team_coach_team" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_coach" ADD CONSTRAINT "FK_team_coach_coach" FOREIGN KEY ("coach_id") REFERENCES "coach"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "season" ADD CONSTRAINT "FK_season_team" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_season_pot" ADD CONSTRAINT "FK_team_season_pot_team" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_season_pot" ADD CONSTRAINT "FK_team_season_pot_season" FOREIGN KEY ("season_id") REFERENCES "season"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "training_log_entry" ADD CONSTRAINT "FK_training_log_entry_player" FOREIGN KEY ("player_id") REFERENCES "player"("id") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "training_log_entry" ADD CONSTRAINT "FK_training_log_entry_team" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE`,
    );
    // Nullable + SET NULL: deleting a Challenge (Phase 2 feature, not built
    // yet) must not destroy historical TrainingLogEntry rows.
    await queryRunner.query(
      `ALTER TABLE "training_log_entry" ADD CONSTRAINT "FK_training_log_entry_challenge" FOREIGN KEY ("challenge_id") REFERENCES "challenge"("id") ON DELETE SET NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "challenge" ADD CONSTRAINT "FK_challenge_team" FOREIGN KEY ("team_id") REFERENCES "team"("id") ON DELETE CASCADE`,
    );
    // RESTRICT: don't silently delete a coach's created challenges by
    // deleting the coach row (no coach-deletion feature exists yet either).
    await queryRunner.query(
      `ALTER TABLE "challenge" ADD CONSTRAINT "FK_challenge_created_by_coach" FOREIGN KEY ("created_by_coach_id") REFERENCES "coach"("id") ON DELETE RESTRICT`,
    );
    await queryRunner.query(
      `ALTER TABLE "badge_award" ADD CONSTRAINT "FK_badge_award_player" FOREIGN KEY ("player_id") REFERENCES "player"("id") ON DELETE CASCADE`,
    );
    // RESTRICT: a badge catalog entry shouldn't be deletable while players
    // still hold awards of it.
    await queryRunner.query(
      `ALTER TABLE "badge_award" ADD CONSTRAINT "FK_badge_award_badge" FOREIGN KEY ("badge_id") REFERENCES "badge"("id") ON DELETE RESTRICT`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "badge_award" DROP CONSTRAINT "FK_badge_award_badge"`,
    );
    await queryRunner.query(
      `ALTER TABLE "badge_award" DROP CONSTRAINT "FK_badge_award_player"`,
    );
    await queryRunner.query(
      `ALTER TABLE "challenge" DROP CONSTRAINT "FK_challenge_created_by_coach"`,
    );
    await queryRunner.query(
      `ALTER TABLE "challenge" DROP CONSTRAINT "FK_challenge_team"`,
    );
    await queryRunner.query(
      `ALTER TABLE "training_log_entry" DROP CONSTRAINT "FK_training_log_entry_challenge"`,
    );
    await queryRunner.query(
      `ALTER TABLE "training_log_entry" DROP CONSTRAINT "FK_training_log_entry_team"`,
    );
    await queryRunner.query(
      `ALTER TABLE "training_log_entry" DROP CONSTRAINT "FK_training_log_entry_player"`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_season_pot" DROP CONSTRAINT "FK_team_season_pot_season"`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_season_pot" DROP CONSTRAINT "FK_team_season_pot_team"`,
    );
    await queryRunner.query(
      `ALTER TABLE "season" DROP CONSTRAINT "FK_season_team"`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_coach" DROP CONSTRAINT "FK_team_coach_coach"`,
    );
    await queryRunner.query(
      `ALTER TABLE "team_coach" DROP CONSTRAINT "FK_team_coach_team"`,
    );
    await queryRunner.query(
      `ALTER TABLE "parental_consent_record" DROP CONSTRAINT "FK_parental_consent_record_player"`,
    );
    await queryRunner.query(
      `ALTER TABLE "player_private_info" DROP CONSTRAINT "FK_player_private_info_player"`,
    );
    await queryRunner.query(
      `ALTER TABLE "player" DROP CONSTRAINT "FK_player_team"`,
    );

    await queryRunner.query(`DROP TABLE "badge_award"`);
    await queryRunner.query(`DROP TABLE "badge"`);
    await queryRunner.query(`DROP TABLE "challenge"`);
    await queryRunner.query(`DROP TYPE "public"."challenge_status_enum"`);
    await queryRunner.query(`DROP TABLE "coach"`);
    await queryRunner.query(`DROP TABLE "parental_consent_record"`);
    await queryRunner.query(`DROP TYPE "public"."consent_method_enum"`);
    await queryRunner.query(`DROP TABLE "player_private_info"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_4ac675ceabf9c0fe1cc21cb232"`,
    );
    await queryRunner.query(`DROP TABLE "team_season_pot"`);
    await queryRunner.query(`DROP TYPE "public"."team_season_pot_status_enum"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_b3c76b4d48cefcb7aa46feb1ee"`,
    );
    await queryRunner.query(`DROP TABLE "player"`);
    // Shared by Player.parental_consent_status and
    // ParentalConsentRecord.status — dropped once, after both tables.
    await queryRunner.query(
      `DROP TYPE "public"."parental_consent_status_enum"`,
    );
    await queryRunner.query(`DROP TABLE "season"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_b97de386b953752f7897d45094"`,
    );
    await queryRunner.query(`DROP TABLE "team_coach"`);
    await queryRunner.query(`DROP TABLE "team"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_913379111b6efeadd470484567"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_4cf1a9969fa2a43f4b4f3416c2"`,
    );
    await queryRunner.query(`DROP TABLE "training_log_entry"`);
    await queryRunner.query(`DROP TYPE "public"."activity_type_enum"`);
  }
}
