import { MigrationInterface, QueryRunner } from 'typeorm';

// Adds what the demo-invite mailing needs to `event_registration`:
//
//  1. `invite_sent_at` — so "send the invites" is idempotent. Without it,
//     an admin clicking twice mails the whole list twice, which is the
//     fastest way to teach people to mark us as spam.
//  2. `unsubscribe_code` — a per-row random code carried in every email.
//     A marketing list without a one-click way out is both bad manners and
//     a real operational risk: spam complaints damage the sending domain's
//     reputation, and the mail that stops being delivered when that
//     happens is the PARENTAL CONSENT email, which everything else in this
//     app depends on. The unsubscribe link protects the consent pipeline
//     at least as much as it protects the recipient.
//
// The code is generated by Postgres (`replace(gen_random_uuid()::text,'-','')`
// — 32 hex chars, no extension needed) rather than by the app, so existing
// rows get one in the same statement that adds the column and the
// application never has to remember to set it.
//
// There is no `unsubscribed_at`. Unsubscribing DELETES the row: keeping a
// tombstone would mean holding someone's email address specifically after
// they asked us to stop, which is the opposite of what they asked for.
export class AddEventRegistrationInvite1786800000000
  implements MigrationInterface
{
  name = 'AddEventRegistrationInvite1786800000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "event_registration"
        ADD COLUMN "invite_sent_at" TIMESTAMP WITH TIME ZONE
    `);
    await queryRunner.query(`
      ALTER TABLE "event_registration"
        ADD COLUMN "unsubscribe_code" character varying(32) NOT NULL
        DEFAULT replace(gen_random_uuid()::text, '-', '')
    `);
    // Unique because it is the only thing identifying the row in an
    // unsubscribe link — a collision would unsubscribe the wrong person.
    await queryRunner.query(`
      CREATE UNIQUE INDEX "UQ_event_registration_unsubscribe_code"
        ON "event_registration" ("unsubscribe_code")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX "UQ_event_registration_unsubscribe_code"`,
    );
    await queryRunner.query(
      `ALTER TABLE "event_registration" DROP COLUMN "unsubscribe_code"`,
    );
    await queryRunner.query(
      `ALTER TABLE "event_registration" DROP COLUMN "invite_sent_at"`,
    );
  }
}
